//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace vin65WS2.com.vin65.webservicesProduct {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductService.cfcSoapBinding", Namespace="http://V300")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Product1))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Error))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Response))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(VintageNote))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Price))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Inventory))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SKU))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Photo))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Media))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BundleItem))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Request))]
    public partial class ProductServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUpdateProductDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchProductsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProductServiceService() {
            this.Url = global::vin65WS2.Properties.Settings.Default.vin65WS2_com_vin65_webservicesProduct_ProductServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductDetailCompletedEventHandler GetProductDetailCompleted;
        
        /// <remarks/>
        public event AddUpdateProductDetailCompletedEventHandler AddUpdateProductDetailCompleted;
        
        /// <remarks/>
        public event SearchProductsCompletedEventHandler SearchProductsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetProductDetailReturn")]
        public Response3 GetProductDetail(Request3 Request) {
            object[] results = this.Invoke("GetProductDetail", new object[] {
                        Request});
            return ((Response3)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductDetailAsync(Request3 Request) {
            this.GetProductDetailAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetProductDetailAsync(Request3 Request, object userState) {
            if ((this.GetProductDetailOperationCompleted == null)) {
                this.GetProductDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductDetailOperationCompleted);
            }
            this.InvokeAsync("GetProductDetail", new object[] {
                        Request}, this.GetProductDetailOperationCompleted, userState);
        }
        
        private void OnGetProductDetailOperationCompleted(object arg) {
            if ((this.GetProductDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductDetailCompleted(this, new GetProductDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
        [return: System.Xml.Serialization.SoapElementAttribute("AddUpdateProductDetailReturn")]
        public Response2 AddUpdateProductDetail(Request2 Request) {
            object[] results = this.Invoke("AddUpdateProductDetail", new object[] {
                        Request});
            return ((Response2)(results[0]));
        }
        
        /// <remarks/>
        public void AddUpdateProductDetailAsync(Request2 Request) {
            this.AddUpdateProductDetailAsync(Request, null);
        }
        
        /// <remarks/>
        public void AddUpdateProductDetailAsync(Request2 Request, object userState) {
            if ((this.AddUpdateProductDetailOperationCompleted == null)) {
                this.AddUpdateProductDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUpdateProductDetailOperationCompleted);
            }
            this.InvokeAsync("AddUpdateProductDetail", new object[] {
                        Request}, this.AddUpdateProductDetailOperationCompleted, userState);
        }
        
        private void OnAddUpdateProductDetailOperationCompleted(object arg) {
            if ((this.AddUpdateProductDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUpdateProductDetailCompleted(this, new AddUpdateProductDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
        [return: System.Xml.Serialization.SoapElementAttribute("SearchProductsReturn")]
        public Response1 SearchProducts(Request1 Request) {
            object[] results = this.Invoke("SearchProducts", new object[] {
                        Request});
            return ((Response1)(results[0]));
        }
        
        /// <remarks/>
        public void SearchProductsAsync(Request1 Request) {
            this.SearchProductsAsync(Request, null);
        }
        
        /// <remarks/>
        public void SearchProductsAsync(Request1 Request, object userState) {
            if ((this.SearchProductsOperationCompleted == null)) {
                this.SearchProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchProductsOperationCompleted);
            }
            this.InvokeAsync("SearchProducts", new object[] {
                        Request}, this.SearchProductsOperationCompleted, userState);
        }
        
        private void OnSearchProductsOperationCompleted(object arg) {
            if ((this.SearchProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchProductsCompleted(this, new SearchProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://getProductDetail.product.V300")]
    public partial class Request3 : Request {
        
        private string productIDField;
        
        private string sKUField;
        
        private string websiteIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string WebsiteID {
            get {
                return this.websiteIDField;
            }
            set {
                this.websiteIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Request3))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Request2))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Request1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.base.V300")]
    public partial class Request {
        
        private Security securityField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Security Security {
            get {
                return this.securityField;
            }
            set {
                this.securityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.base.V300")]
    public partial class Security {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="Product", Namespace="http://searchProducts.product.V300")]
    public partial class Product1 {
        
        private string brandField;
        
        private System.Nullable<System.DateTime> dateModifiedField;
        
        private System.Nullable<double> priceField;
        
        private string productIDField;
        
        private string sKUField;
        
        private System.Nullable<double> salePriceField;
        
        private string titleField;
        
        private string typeField;
        
        private System.Nullable<double> vintageField;
        
        private string websiteIDField;
        
        private System.Nullable<bool> isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> SalePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Vintage {
            get {
                return this.vintageField;
            }
            set {
                this.vintageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string WebsiteID {
            get {
                return this.websiteIDField;
            }
            set {
                this.websiteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V300")]
    public partial class Error {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Response3))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Response2))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Response1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V300")]
    public partial class Response {
        
        private Error[] errorsField;
        
        private System.Nullable<bool> isSuccessfulField;
        
        private System.Nullable<double> recordCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://getProductDetail.product.V300")]
    public partial class Response3 : Response {
        
        private Product productField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Product Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class Product {
        
        private string actionMessageField;
        
        private string brandField;
        
        private BundleItem[] bundleItemsField;
        
        private System.Nullable<System.DateTime> dateAddedField;
        
        private System.Nullable<System.DateTime> dateModifiedField;
        
        private Description descriptionField;
        
        private System.Nullable<bool> isActiveField;
        
        private System.Nullable<bool> isDisplayOnWebsiteField;
        
        private Media[] mediaField;
        
        private string pOSTitleField;
        
        private Photo[] photosField;
        
        private string productIDField;
        
        private SKU[] sKUsField;
        
        private SpiritProperties spiritPropertiesField;
        
        private string subTitleField;
        
        private string titleField;
        
        private string typeField;
        
        private VintageNote[] vintageNotesField;
        
        private string websiteIDField;
        
        private WineProperties winePropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ActionMessage {
            get {
                return this.actionMessageField;
            }
            set {
                this.actionMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public BundleItem[] BundleItems {
            get {
                return this.bundleItemsField;
            }
            set {
                this.bundleItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                this.dateAddedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Description Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDisplayOnWebsite {
            get {
                return this.isDisplayOnWebsiteField;
            }
            set {
                this.isDisplayOnWebsiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Media[] Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string POSTitle {
            get {
                return this.pOSTitleField;
            }
            set {
                this.pOSTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Photo[] Photos {
            get {
                return this.photosField;
            }
            set {
                this.photosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public SKU[] SKUs {
            get {
                return this.sKUsField;
            }
            set {
                this.sKUsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public SpiritProperties SpiritProperties {
            get {
                return this.spiritPropertiesField;
            }
            set {
                this.spiritPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SubTitle {
            get {
                return this.subTitleField;
            }
            set {
                this.subTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public VintageNote[] VintageNotes {
            get {
                return this.vintageNotesField;
            }
            set {
                this.vintageNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string WebsiteID {
            get {
                return this.websiteIDField;
            }
            set {
                this.websiteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public WineProperties WineProperties {
            get {
                return this.winePropertiesField;
            }
            set {
                this.winePropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class BundleItem {
        
        private System.Nullable<double> quantityField;
        
        private string sKUField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class Description {
        
        private string description1Field;
        
        private string teaserField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("Description", IsNullable=true)]
        public string Description1 {
            get {
                return this.description1Field;
            }
            set {
                this.description1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Teaser {
            get {
                return this.teaserField;
            }
            set {
                this.teaserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class Media {
        
        private string captionField;
        
        private System.Nullable<double> displayOrderField;
        
        private string fileField;
        
        private string thumbnailField;
        
        private string titleField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class Photo {
        
        private string captionField;
        
        private System.Nullable<double> displayOrderField;
        
        private string photo1Field;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("Photo", IsNullable=true)]
        public string Photo1 {
            get {
                return this.photo1Field;
            }
            set {
                this.photo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class SKU {
        
        private System.Nullable<double> costOfGoodField;
        
        private System.Nullable<double> displayOrderField;
        
        private Inventory[] inventoryField;
        
        private System.Nullable<bool> isInventoryOnField;
        
        private System.Nullable<bool> isNoShippingChargeField;
        
        private System.Nullable<bool> isNonTaxableField;
        
        private System.Nullable<double> maxOrderQtyField;
        
        private System.Nullable<double> minOrderQtyField;
        
        private System.Nullable<double> orderInMultiplesOfField;
        
        private Price[] pricesField;
        
        private string sKU1Field;
        
        private string uPCCodeField;
        
        private string unitDescriptionField;
        
        private System.Nullable<double> weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> CostOfGood {
            get {
                return this.costOfGoodField;
            }
            set {
                this.costOfGoodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Inventory[] Inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsInventoryOn {
            get {
                return this.isInventoryOnField;
            }
            set {
                this.isInventoryOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsNoShippingCharge {
            get {
                return this.isNoShippingChargeField;
            }
            set {
                this.isNoShippingChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsNonTaxable {
            get {
                return this.isNonTaxableField;
            }
            set {
                this.isNonTaxableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> MaxOrderQty {
            get {
                return this.maxOrderQtyField;
            }
            set {
                this.maxOrderQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> MinOrderQty {
            get {
                return this.minOrderQtyField;
            }
            set {
                this.minOrderQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> OrderInMultiplesOf {
            get {
                return this.orderInMultiplesOfField;
            }
            set {
                this.orderInMultiplesOfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Price[] Prices {
            get {
                return this.pricesField;
            }
            set {
                this.pricesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("SKU", IsNullable=true)]
        public string SKU1 {
            get {
                return this.sKU1Field;
            }
            set {
                this.sKU1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string UPCCode {
            get {
                return this.uPCCodeField;
            }
            set {
                this.uPCCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string UnitDescription {
            get {
                return this.unitDescriptionField;
            }
            set {
                this.unitDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class Inventory {
        
        private System.Nullable<double> currentInventoryField;
        
        private string inventoryPoolField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> CurrentInventory {
            get {
                return this.currentInventoryField;
            }
            set {
                this.currentInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string InventoryPool {
            get {
                return this.inventoryPoolField;
            }
            set {
                this.inventoryPoolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class Price {
        
        private System.Nullable<double> price1Field;
        
        private string priceLevelField;
        
        private System.Nullable<double> priceQuantityField;
        
        private System.Nullable<double> salePriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("Price", IsNullable=true)]
        public System.Nullable<double> Price1 {
            get {
                return this.price1Field;
            }
            set {
                this.price1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string PriceLevel {
            get {
                return this.priceLevelField;
            }
            set {
                this.priceLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> PriceQuantity {
            get {
                return this.priceQuantityField;
            }
            set {
                this.priceQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> SalePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class SpiritProperties {
        
        private string countryField;
        
        private string regionField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class VintageNote {
        
        private string noteField;
        
        private System.Nullable<double> vintageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Vintage {
            get {
                return this.vintageField;
            }
            set {
                this.vintageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_product.product.V300")]
    public partial class WineProperties {
        
        private string acidField;
        
        private string alcoholField;
        
        private string appellationField;
        
        private System.Nullable<double> avgRatingField;
        
        private string awardsField;
        
        private string bottleSizeField;
        
        private System.Nullable<double> bottleSizeInMLField;
        
        private System.Nullable<double> bottlesInCaseField;
        
        private string bottlingDateField;
        
        private System.Nullable<double> cGRatingField;
        
        private string fermentationField;
        
        private string foodPairingNotesField;
        
        private string harvestDateField;
        
        private System.Nullable<double> jHRatingField;
        
        private string otherNotesField;
        
        private string phField;
        
        private string productionField;
        
        private string productionNotesField;
        
        private System.Nullable<double> rPRatingField;
        
        private string ratingsField;
        
        private string regionField;
        
        private string residualSugarField;
        
        private System.Nullable<double> sTRatingField;
        
        private string sugarField;
        
        private string tanninField;
        
        private string tastingNotesField;
        
        private string typeField;
        
        private string varietalField;
        
        private string vineyardDesignationField;
        
        private string vineyardNotesField;
        
        private System.Nullable<double> vintageField;
        
        private System.Nullable<double> wARatingField;
        
        private System.Nullable<double> wAndSRatingField;
        
        private System.Nullable<double> wBRatingField;
        
        private System.Nullable<double> wERatingField;
        
        private System.Nullable<double> wNRatingField;
        
        private System.Nullable<double> wSRatingField;
        
        private string wineMakerNotesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Acid {
            get {
                return this.acidField;
            }
            set {
                this.acidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Alcohol {
            get {
                return this.alcoholField;
            }
            set {
                this.alcoholField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Appellation {
            get {
                return this.appellationField;
            }
            set {
                this.appellationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> AvgRating {
            get {
                return this.avgRatingField;
            }
            set {
                this.avgRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Awards {
            get {
                return this.awardsField;
            }
            set {
                this.awardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string BottleSize {
            get {
                return this.bottleSizeField;
            }
            set {
                this.bottleSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> BottleSizeInML {
            get {
                return this.bottleSizeInMLField;
            }
            set {
                this.bottleSizeInMLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> BottlesInCase {
            get {
                return this.bottlesInCaseField;
            }
            set {
                this.bottlesInCaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string BottlingDate {
            get {
                return this.bottlingDateField;
            }
            set {
                this.bottlingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> CGRating {
            get {
                return this.cGRatingField;
            }
            set {
                this.cGRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Fermentation {
            get {
                return this.fermentationField;
            }
            set {
                this.fermentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string FoodPairingNotes {
            get {
                return this.foodPairingNotesField;
            }
            set {
                this.foodPairingNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string HarvestDate {
            get {
                return this.harvestDateField;
            }
            set {
                this.harvestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> JHRating {
            get {
                return this.jHRatingField;
            }
            set {
                this.jHRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string OtherNotes {
            get {
                return this.otherNotesField;
            }
            set {
                this.otherNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string PH {
            get {
                return this.phField;
            }
            set {
                this.phField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Production {
            get {
                return this.productionField;
            }
            set {
                this.productionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ProductionNotes {
            get {
                return this.productionNotesField;
            }
            set {
                this.productionNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> RPRating {
            get {
                return this.rPRatingField;
            }
            set {
                this.rPRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Ratings {
            get {
                return this.ratingsField;
            }
            set {
                this.ratingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ResidualSugar {
            get {
                return this.residualSugarField;
            }
            set {
                this.residualSugarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> STRating {
            get {
                return this.sTRatingField;
            }
            set {
                this.sTRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Sugar {
            get {
                return this.sugarField;
            }
            set {
                this.sugarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Tannin {
            get {
                return this.tanninField;
            }
            set {
                this.tanninField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string TastingNotes {
            get {
                return this.tastingNotesField;
            }
            set {
                this.tastingNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Varietal {
            get {
                return this.varietalField;
            }
            set {
                this.varietalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string VineyardDesignation {
            get {
                return this.vineyardDesignationField;
            }
            set {
                this.vineyardDesignationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string VineyardNotes {
            get {
                return this.vineyardNotesField;
            }
            set {
                this.vineyardNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Vintage {
            get {
                return this.vintageField;
            }
            set {
                this.vintageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> WARating {
            get {
                return this.wARatingField;
            }
            set {
                this.wARatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> WAndSRating {
            get {
                return this.wAndSRatingField;
            }
            set {
                this.wAndSRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> WBRating {
            get {
                return this.wBRatingField;
            }
            set {
                this.wBRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> WERating {
            get {
                return this.wERatingField;
            }
            set {
                this.wERatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> WNRating {
            get {
                return this.wNRatingField;
            }
            set {
                this.wNRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> WSRating {
            get {
                return this.wSRatingField;
            }
            set {
                this.wSRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string WineMakerNotes {
            get {
                return this.wineMakerNotesField;
            }
            set {
                this.wineMakerNotesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://addUpdateProductDetail.product.V300")]
    public partial class Response2 : Response {
        
        private string productIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://searchProducts.product.V300")]
    public partial class Response1 : Response {
        
        private Product1[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Product1[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://addUpdateProductDetail.product.V300")]
    public partial class Request2 : Request {
        
        private string modeField;
        
        private Product productField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Product Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://searchProducts.product.V300")]
    public partial class Request1 : Request {
        
        private System.Nullable<System.DateTime> dateModifiedFromField;
        
        private System.Nullable<System.DateTime> dateModifiedToField;
        
        private System.Nullable<bool> isActiveField;
        
        private System.Nullable<double> maxRowsField;
        
        private System.Nullable<double> pageField;
        
        private string productIDField;
        
        private string sKUField;
        
        private string sortByField;
        
        private string titleField;
        
        private string typeField;
        
        private string websiteIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateModifiedFrom {
            get {
                return this.dateModifiedFromField;
            }
            set {
                this.dateModifiedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateModifiedTo {
            get {
                return this.dateModifiedToField;
            }
            set {
                this.dateModifiedToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> MaxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string WebsiteIDs {
            get {
                return this.websiteIDsField;
            }
            set {
                this.websiteIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetProductDetailCompletedEventHandler(object sender, GetProductDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response3 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response3)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddUpdateProductDetailCompletedEventHandler(object sender, AddUpdateProductDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUpdateProductDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUpdateProductDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SearchProductsCompletedEventHandler(object sender, SearchProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response1)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591