//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ContactService.cfcSoapBinding", Namespace="http://V300")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_MergedContact))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_ShippingAddress))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Error))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request))]
public partial class CS_ContactServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetContactOperationCompleted;
    
    private System.Threading.SendOrPostCallback SearchContactTypesOperationCompleted;
    
    private System.Threading.SendOrPostCallback MergeContactOperationCompleted;
    
    private System.Threading.SendOrPostCallback RemoveContactTypeFromContactOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddContactTypeToContactOperationCompleted;
    
    private System.Threading.SendOrPostCallback SearchContactsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SearchShippingAddressesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetContactStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetContactTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddUpdateContactTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback SearchMergedContactsOperationCompleted;
    
    /// <remarks/>
    public CS_ContactServiceService() {
        this.Url = "http://webservices.vin65.com/V300/ContactService.cfc";
    }
    
    /// <remarks/>
    public event CS_GetContactCompletedEventHandler GetContactCompleted;
    
    /// <remarks/>
    public event CS_SearchContactTypesCompletedEventHandler SearchContactTypesCompleted;
    
    /// <remarks/>
    public event CS_MergeContactCompletedEventHandler MergeContactCompleted;
    
    /// <remarks/>
    public event CS_RemoveContactTypeFromContactCompletedEventHandler RemoveContactTypeFromContactCompleted;
    
    /// <remarks/>
    public event CS_AddContactTypeToContactCompletedEventHandler AddContactTypeToContactCompleted;
    
    /// <remarks/>
    public event CS_SearchContactsCompletedEventHandler SearchContactsCompleted;
    
    /// <remarks/>
    public event CS_SearchShippingAddressesCompletedEventHandler SearchShippingAddressesCompleted;
    
    /// <remarks/>
    public event CS_GetContactStatusCompletedEventHandler GetContactStatusCompleted;
    
    /// <remarks/>
    public event CS_GetContactTypeCompletedEventHandler GetContactTypeCompleted;
    
    /// <remarks/>
    public event CS_AddUpdateContactTypeCompletedEventHandler AddUpdateContactTypeCompleted;
    
    /// <remarks/>
    public event CS_SearchMergedContactsCompletedEventHandler SearchMergedContactsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("GetContactReturn")]
    public CS_Response5 GetContact(CS_Request5 Request) {
        object[] results = this.Invoke("GetContact", new object[] {
                    Request});
        return ((CS_Response5)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetContact(CS_Request5 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetContact", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response5 EndGetContact(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response5)(results[0]));
    }
    
    /// <remarks/>
    public void GetContactAsync(CS_Request5 Request) {
        this.GetContactAsync(Request, null);
    }
    
    /// <remarks/>
    public void GetContactAsync(CS_Request5 Request, object userState) {
        if ((this.GetContactOperationCompleted == null)) {
            this.GetContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactOperationCompleted);
        }
        this.InvokeAsync("GetContact", new object[] {
                    Request}, this.GetContactOperationCompleted, userState);
    }
    
    private void OnGetContactOperationCompleted(object arg) {
        if ((this.GetContactCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetContactCompleted(this, new CS_GetContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("SearchContactTypesReturn")]
    public CS_Response2 SearchContactTypes(CS_Request2 Request) {
        object[] results = this.Invoke("SearchContactTypes", new object[] {
                    Request});
        return ((CS_Response2)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSearchContactTypes(CS_Request2 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SearchContactTypes", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response2 EndSearchContactTypes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response2)(results[0]));
    }
    
    /// <remarks/>
    public void SearchContactTypesAsync(CS_Request2 Request) {
        this.SearchContactTypesAsync(Request, null);
    }
    
    /// <remarks/>
    public void SearchContactTypesAsync(CS_Request2 Request, object userState) {
        if ((this.SearchContactTypesOperationCompleted == null)) {
            this.SearchContactTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchContactTypesOperationCompleted);
        }
        this.InvokeAsync("SearchContactTypes", new object[] {
                    Request}, this.SearchContactTypesOperationCompleted, userState);
    }
    
    private void OnSearchContactTypesOperationCompleted(object arg) {
        if ((this.SearchContactTypesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SearchContactTypesCompleted(this, new CS_SearchContactTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("MergeContactReturn")]
    public CS_Response4 MergeContact(CS_Request4 Request) {
        object[] results = this.Invoke("MergeContact", new object[] {
                    Request});
        return ((CS_Response4)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMergeContact(CS_Request4 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MergeContact", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response4 EndMergeContact(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response4)(results[0]));
    }
    
    /// <remarks/>
    public void MergeContactAsync(CS_Request4 Request) {
        this.MergeContactAsync(Request, null);
    }
    
    /// <remarks/>
    public void MergeContactAsync(CS_Request4 Request, object userState) {
        if ((this.MergeContactOperationCompleted == null)) {
            this.MergeContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMergeContactOperationCompleted);
        }
        this.InvokeAsync("MergeContact", new object[] {
                    Request}, this.MergeContactOperationCompleted, userState);
    }
    
    private void OnMergeContactOperationCompleted(object arg) {
        if ((this.MergeContactCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MergeContactCompleted(this, new CS_MergeContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("RemoveContactTypeFromContactReturn")]
    public CS_Response9 RemoveContactTypeFromContact(CS_Request9 Request) {
        object[] results = this.Invoke("RemoveContactTypeFromContact", new object[] {
                    Request});
        return ((CS_Response9)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRemoveContactTypeFromContact(CS_Request9 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RemoveContactTypeFromContact", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response9 EndRemoveContactTypeFromContact(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response9)(results[0]));
    }
    
    /// <remarks/>
    public void RemoveContactTypeFromContactAsync(CS_Request9 Request) {
        this.RemoveContactTypeFromContactAsync(Request, null);
    }
    
    /// <remarks/>
    public void RemoveContactTypeFromContactAsync(CS_Request9 Request, object userState) {
        if ((this.RemoveContactTypeFromContactOperationCompleted == null)) {
            this.RemoveContactTypeFromContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveContactTypeFromContactOperationCompleted);
        }
        this.InvokeAsync("RemoveContactTypeFromContact", new object[] {
                    Request}, this.RemoveContactTypeFromContactOperationCompleted, userState);
    }
    
    private void OnRemoveContactTypeFromContactOperationCompleted(object arg) {
        if ((this.RemoveContactTypeFromContactCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RemoveContactTypeFromContactCompleted(this, new CS_RemoveContactTypeFromContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("AddContactTypeToContactReturn")]
    public CS_Response6 AddContactTypeToContact(CS_Request6 Request) {
        object[] results = this.Invoke("AddContactTypeToContact", new object[] {
                    Request});
        return ((CS_Response6)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddContactTypeToContact(CS_Request6 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddContactTypeToContact", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response6 EndAddContactTypeToContact(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response6)(results[0]));
    }
    
    /// <remarks/>
    public void AddContactTypeToContactAsync(CS_Request6 Request) {
        this.AddContactTypeToContactAsync(Request, null);
    }
    
    /// <remarks/>
    public void AddContactTypeToContactAsync(CS_Request6 Request, object userState) {
        if ((this.AddContactTypeToContactOperationCompleted == null)) {
            this.AddContactTypeToContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddContactTypeToContactOperationCompleted);
        }
        this.InvokeAsync("AddContactTypeToContact", new object[] {
                    Request}, this.AddContactTypeToContactOperationCompleted, userState);
    }
    
    private void OnAddContactTypeToContactOperationCompleted(object arg) {
        if ((this.AddContactTypeToContactCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddContactTypeToContactCompleted(this, new CS_AddContactTypeToContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("SearchContactsReturn")]
    public CS_Response7 SearchContacts(CS_Request7 Request) {
        object[] results = this.Invoke("SearchContacts", new object[] {
                    Request});
        return ((CS_Response7)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSearchContacts(CS_Request7 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SearchContacts", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response7 EndSearchContacts(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response7)(results[0]));
    }
    
    /// <remarks/>
    public void SearchContactsAsync(CS_Request7 Request) {
        this.SearchContactsAsync(Request, null);
    }
    
    /// <remarks/>
    public void SearchContactsAsync(CS_Request7 Request, object userState) {
        if ((this.SearchContactsOperationCompleted == null)) {
            this.SearchContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchContactsOperationCompleted);
        }
        this.InvokeAsync("SearchContacts", new object[] {
                    Request}, this.SearchContactsOperationCompleted, userState);
    }
    
    private void OnSearchContactsOperationCompleted(object arg) {
        if ((this.SearchContactsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SearchContactsCompleted(this, new CS_SearchContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("SearchShippingAddressesReturn")]
    public CS_Response1 SearchShippingAddresses(CS_Request1 Request) {
        object[] results = this.Invoke("SearchShippingAddresses", new object[] {
                    Request});
        return ((CS_Response1)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSearchShippingAddresses(CS_Request1 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SearchShippingAddresses", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response1 EndSearchShippingAddresses(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response1)(results[0]));
    }
    
    /// <remarks/>
    public void SearchShippingAddressesAsync(CS_Request1 Request) {
        this.SearchShippingAddressesAsync(Request, null);
    }
    
    /// <remarks/>
    public void SearchShippingAddressesAsync(CS_Request1 Request, object userState) {
        if ((this.SearchShippingAddressesOperationCompleted == null)) {
            this.SearchShippingAddressesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchShippingAddressesOperationCompleted);
        }
        this.InvokeAsync("SearchShippingAddresses", new object[] {
                    Request}, this.SearchShippingAddressesOperationCompleted, userState);
    }
    
    private void OnSearchShippingAddressesOperationCompleted(object arg) {
        if ((this.SearchShippingAddressesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SearchShippingAddressesCompleted(this, new CS_SearchShippingAddressesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("GetContactStatusReturn")]
    public CS_Response3 GetContactStatus(CS_Request3 Request) {
        object[] results = this.Invoke("GetContactStatus", new object[] {
                    Request});
        return ((CS_Response3)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetContactStatus(CS_Request3 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetContactStatus", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response3 EndGetContactStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response3)(results[0]));
    }
    
    /// <remarks/>
    public void GetContactStatusAsync(CS_Request3 Request) {
        this.GetContactStatusAsync(Request, null);
    }
    
    /// <remarks/>
    public void GetContactStatusAsync(CS_Request3 Request, object userState) {
        if ((this.GetContactStatusOperationCompleted == null)) {
            this.GetContactStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactStatusOperationCompleted);
        }
        this.InvokeAsync("GetContactStatus", new object[] {
                    Request}, this.GetContactStatusOperationCompleted, userState);
    }
    
    private void OnGetContactStatusOperationCompleted(object arg) {
        if ((this.GetContactStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetContactStatusCompleted(this, new CS_GetContactStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("GetContactTypeReturn")]
    public CS_Response10 GetContactType(CS_Request10 Request) {
        object[] results = this.Invoke("GetContactType", new object[] {
                    Request});
        return ((CS_Response10)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetContactType(CS_Request10 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetContactType", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response10 EndGetContactType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response10)(results[0]));
    }
    
    /// <remarks/>
    public void GetContactTypeAsync(CS_Request10 Request) {
        this.GetContactTypeAsync(Request, null);
    }
    
    /// <remarks/>
    public void GetContactTypeAsync(CS_Request10 Request, object userState) {
        if ((this.GetContactTypeOperationCompleted == null)) {
            this.GetContactTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactTypeOperationCompleted);
        }
        this.InvokeAsync("GetContactType", new object[] {
                    Request}, this.GetContactTypeOperationCompleted, userState);
    }
    
    private void OnGetContactTypeOperationCompleted(object arg) {
        if ((this.GetContactTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetContactTypeCompleted(this, new CS_GetContactTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("AddUpdateContactTypeReturn")]
    public CS_Response8 AddUpdateContactType(CS_Request8 Request) {
        object[] results = this.Invoke("AddUpdateContactType", new object[] {
                    Request});
        return ((CS_Response8)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddUpdateContactType(CS_Request8 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddUpdateContactType", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response8 EndAddUpdateContactType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response8)(results[0]));
    }
    
    /// <remarks/>
    public void AddUpdateContactTypeAsync(CS_Request8 Request) {
        this.AddUpdateContactTypeAsync(Request, null);
    }
    
    /// <remarks/>
    public void AddUpdateContactTypeAsync(CS_Request8 Request, object userState) {
        if ((this.AddUpdateContactTypeOperationCompleted == null)) {
            this.AddUpdateContactTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUpdateContactTypeOperationCompleted);
        }
        this.InvokeAsync("AddUpdateContactType", new object[] {
                    Request}, this.AddUpdateContactTypeOperationCompleted, userState);
    }
    
    private void OnAddUpdateContactTypeOperationCompleted(object arg) {
        if ((this.AddUpdateContactTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddUpdateContactTypeCompleted(this, new CS_AddUpdateContactTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("SearchMergedContactsReturn")]
    public CS_Response11 SearchMergedContacts(CS_Request11 Request) {
        object[] results = this.Invoke("SearchMergedContacts", new object[] {
                    Request});
        return ((CS_Response11)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSearchMergedContacts(CS_Request11 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SearchMergedContacts", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public CS_Response11 EndSearchMergedContacts(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CS_Response11)(results[0]));
    }
    
    /// <remarks/>
    public void SearchMergedContactsAsync(CS_Request11 Request) {
        this.SearchMergedContactsAsync(Request, null);
    }
    
    /// <remarks/>
    public void SearchMergedContactsAsync(CS_Request11 Request, object userState) {
        if ((this.SearchMergedContactsOperationCompleted == null)) {
            this.SearchMergedContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchMergedContactsOperationCompleted);
        }
        this.InvokeAsync("SearchMergedContacts", new object[] {
                    Request}, this.SearchMergedContactsOperationCompleted, userState);
    }
    
    private void OnSearchMergedContactsOperationCompleted(object arg) {
        if ((this.SearchMergedContactsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SearchMergedContactsCompleted(this, new CS_SearchMergedContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://getContact.contact.V300")]
public partial class CS_Request5 : CS_Request {
    
    private string altContactIDField;
    
    private string contactIDField;
    
    private string customerNumberField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string AltContactID {
        get {
            return this.altContactIDField;
        }
        set {
            this.altContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request11))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request10))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request9))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request8))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request7))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request6))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request5))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request4))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request3))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request2))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Request1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.base.V300")]
public partial class CS_Request {
    
    private CS_Security securityField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_Security Security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.base.V300")]
public partial class CS_Security {
    
    private string passwordField;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_contact.contact.V300")]
public partial class CS_MergedContact {
    
    private string contactIDField;
    
    private System.Nullable<System.DateTime> dateMergedField;
    
    private string mergedIntoContactIDField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateMerged {
        get {
            return this.dateMergedField;
        }
        set {
            this.dateMergedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string MergedIntoContactID {
        get {
            return this.mergedIntoContactIDField;
        }
        set {
            this.mergedIntoContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_contact.contact.V300")]
public partial class CS_Contact {
    
    private string addressField;
    
    private string address2Field;
    
    private System.Nullable<System.DateTime> birthDateField;
    
    private string cityField;
    
    private string companyField;
    
    private string contactIDField;
    
    private string countryCodeField;
    
    private System.Nullable<double> customerNumberField;
    
    private System.Nullable<System.DateTime> dateAddedField;
    
    private System.Nullable<System.DateTime> dateModifiedField;
    
    private string emailField;
    
    private string emailStatusField;
    
    private string firstNameField;
    
    private System.Nullable<bool> isNonTaxableField;
    
    private System.Nullable<System.DateTime> lastLoginDateField;
    
    private string lastNameField;
    
    private System.Nullable<System.DateTime> lastOrderDateField;
    
    private System.Nullable<double> lifetimeValueField;
    
    private string masterContactIDField;
    
    private System.Nullable<double> orderCountField;
    
    private string phoneField;
    
    private string sourceCodeField;
    
    private string stateCodeField;
    
    private string titleField;
    
    private string usernameField;
    
    private string websiteIDField;
    
    private string wholesaleNumberField;
    
    private string zipCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateAdded {
        get {
            return this.dateAddedField;
        }
        set {
            this.dateAddedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModified {
        get {
            return this.dateModifiedField;
        }
        set {
            this.dateModifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string EmailStatus {
        get {
            return this.emailStatusField;
        }
        set {
            this.emailStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsNonTaxable {
        get {
            return this.isNonTaxableField;
        }
        set {
            this.isNonTaxableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> LastLoginDate {
        get {
            return this.lastLoginDateField;
        }
        set {
            this.lastLoginDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> LastOrderDate {
        get {
            return this.lastOrderDateField;
        }
        set {
            this.lastOrderDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> LifetimeValue {
        get {
            return this.lifetimeValueField;
        }
        set {
            this.lifetimeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string MasterContactID {
        get {
            return this.masterContactIDField;
        }
        set {
            this.masterContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderCount {
        get {
            return this.orderCountField;
        }
        set {
            this.orderCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SourceCode {
        get {
            return this.sourceCodeField;
        }
        set {
            this.sourceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WholesaleNumber {
        get {
            return this.wholesaleNumberField;
        }
        set {
            this.wholesaleNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_contact.contact.V300")]
public partial class CS_ShippingAddress {
    
    private string addressField;
    
    private string address2Field;
    
    private System.Nullable<System.DateTime> birthdateField;
    
    private string cityField;
    
    private string companyField;
    
    private string contactIDField;
    
    private string countryCodeField;
    
    private System.Nullable<System.DateTime> dateAddedField;
    
    private System.Nullable<System.DateTime> dateModifiedField;
    
    private string emailField;
    
    private string firstnameField;
    
    private string lastnameField;
    
    private string phoneField;
    
    private string shippingAddressIDField;
    
    private string stateCodeField;
    
    private string websiteIDField;
    
    private string zipCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> Birthdate {
        get {
            return this.birthdateField;
        }
        set {
            this.birthdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateAdded {
        get {
            return this.dateAddedField;
        }
        set {
            this.dateAddedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModified {
        get {
            return this.dateModifiedField;
        }
        set {
            this.dateModifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Firstname {
        get {
            return this.firstnameField;
        }
        set {
            this.firstnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Lastname {
        get {
            return this.lastnameField;
        }
        set {
            this.lastnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingAddressID {
        get {
            return this.shippingAddressIDField;
        }
        set {
            this.shippingAddressIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V300")]
public partial class CS_Error {
    
    private string errorCodeField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response11))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response10))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response9))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response8))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response7))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response6))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response5))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response4))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response3))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response2))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CS_Response1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V300")]
public partial class CS_Response {
    
    private CS_Error[] errorsField;
    
    private System.Nullable<bool> isSuccessfulField;
    
    private System.Nullable<double> recordCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_Error[] Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsSuccessful {
        get {
            return this.isSuccessfulField;
        }
        set {
            this.isSuccessfulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> RecordCount {
        get {
            return this.recordCountField;
        }
        set {
            this.recordCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://searchMergedContacts.contact.V300")]
public partial class CS_Response11 : CS_Response {
    
    private CS_MergedContact[] mergedContactsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_MergedContact[] MergedContacts {
        get {
            return this.mergedContactsField;
        }
        set {
            this.mergedContactsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://getContactType.contact.V300")]
public partial class CS_Response10 : CS_Response {
    
    private CS_ContactType contactTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_ContactType ContactType {
        get {
            return this.contactTypeField;
        }
        set {
            this.contactTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_contact.contact.V300")]
public partial class CS_ContactType {
    
    private string contactType1Field;
    
    private string contactTypeIDField;
    
    private System.Nullable<System.DateTime> dateAddedField;
    
    private System.Nullable<System.DateTime> dateModifiedField;
    
    private string isPublicField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute("ContactType", IsNullable=true)]
    public string ContactType1 {
        get {
            return this.contactType1Field;
        }
        set {
            this.contactType1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactTypeID {
        get {
            return this.contactTypeIDField;
        }
        set {
            this.contactTypeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateAdded {
        get {
            return this.dateAddedField;
        }
        set {
            this.dateAddedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModified {
        get {
            return this.dateModifiedField;
        }
        set {
            this.dateModifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string IsPublic {
        get {
            return this.isPublicField;
        }
        set {
            this.isPublicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://removeContactTypeFromContact.contact.V300")]
public partial class CS_Response9 : CS_Response {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://addUpdateContactType.contact.V300")]
public partial class CS_Response8 : CS_Response {
    
    private string contactTypeIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactTypeID {
        get {
            return this.contactTypeIDField;
        }
        set {
            this.contactTypeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://searchContacts.contact.V300")]
public partial class CS_Response7 : CS_Response {
    
    private CS_Contact[] contactsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_Contact[] Contacts {
        get {
            return this.contactsField;
        }
        set {
            this.contactsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://addContactTypeToContact.contact.V300")]
public partial class CS_Response6 : CS_Response {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://getContact.contact.V300")]
public partial class CS_Response5 : CS_Response {
    
    private CS_Contact contactField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_Contact Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://mergeContact.contact.V300")]
public partial class CS_Response4 : CS_Response {
    
    private string contactIDField;
    
    private string mergeIntoContactIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string MergeIntoContactID {
        get {
            return this.mergeIntoContactIDField;
        }
        set {
            this.mergeIntoContactIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://getContactStatus.contact.V300")]
public partial class CS_Response3 : CS_Response {
    
    private System.Nullable<bool> isClubMemberField;
    
    private System.Nullable<bool> isPurchaserField;
    
    private System.Nullable<bool> isSubscriberField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsClubMember {
        get {
            return this.isClubMemberField;
        }
        set {
            this.isClubMemberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsPurchaser {
        get {
            return this.isPurchaserField;
        }
        set {
            this.isPurchaserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsSubscriber {
        get {
            return this.isSubscriberField;
        }
        set {
            this.isSubscriberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://searchContactTypes.contact.V300")]
public partial class CS_Response2 : CS_Response {
    
    private CS_ContactType[] contactTypesField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_ContactType[] ContactTypes {
        get {
            return this.contactTypesField;
        }
        set {
            this.contactTypesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://searchShippingAddresses.contact.V300")]
public partial class CS_Response1 : CS_Response {
    
    private CS_ShippingAddress[] shippingAddressesField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_ShippingAddress[] ShippingAddresses {
        get {
            return this.shippingAddressesField;
        }
        set {
            this.shippingAddressesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://searchMergedContacts.contact.V300")]
public partial class CS_Request11 : CS_Request {
    
    private string contactIDField;
    
    private System.Nullable<System.DateTime> dateMergedFromField;
    
    private System.Nullable<System.DateTime> dateMergedToField;
    
    private System.Nullable<double> maxRowsField;
    
    private System.Nullable<double> pageField;
    
    private string websiteIDsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateMergedFrom {
        get {
            return this.dateMergedFromField;
        }
        set {
            this.dateMergedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateMergedTo {
        get {
            return this.dateMergedToField;
        }
        set {
            this.dateMergedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> MaxRows {
        get {
            return this.maxRowsField;
        }
        set {
            this.maxRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteIDs {
        get {
            return this.websiteIDsField;
        }
        set {
            this.websiteIDsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://getContactType.contact.V300")]
public partial class CS_Request10 : CS_Request {
    
    private string contactTypeIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactTypeID {
        get {
            return this.contactTypeIDField;
        }
        set {
            this.contactTypeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://removeContactTypeFromContact.contact.V300")]
public partial class CS_Request9 : CS_Request {
    
    private string contactIDField;
    
    private string contactTypeIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactTypeID {
        get {
            return this.contactTypeIDField;
        }
        set {
            this.contactTypeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://addUpdateContactType.contact.V300")]
public partial class CS_Request8 : CS_Request {
    
    private CS_ContactType contactTypeField;
    
    private string modeField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public CS_ContactType ContactType {
        get {
            return this.contactTypeField;
        }
        set {
            this.contactTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://searchContacts.contact.V300")]
public partial class CS_Request7 : CS_Request {
    
    private string altContactIDField;
    
    private string cityField;
    
    private string companyField;
    
    private string contactIDField;
    
    private string contactTypeField;
    
    private System.Nullable<double> customerNumberField;
    
    private System.Nullable<System.DateTime> dateModifiedFromField;
    
    private System.Nullable<System.DateTime> dateModifiedToField;
    
    private string emailField;
    
    private string emailStatusField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private System.Nullable<double> maxRowsField;
    
    private System.Nullable<double> pageField;
    
    private string phoneField;
    
    private string sortByField;
    
    private string stateCodeField;
    
    private string websiteIDsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string AltContactID {
        get {
            return this.altContactIDField;
        }
        set {
            this.altContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactType {
        get {
            return this.contactTypeField;
        }
        set {
            this.contactTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedFrom {
        get {
            return this.dateModifiedFromField;
        }
        set {
            this.dateModifiedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedTo {
        get {
            return this.dateModifiedToField;
        }
        set {
            this.dateModifiedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string EmailStatus {
        get {
            return this.emailStatusField;
        }
        set {
            this.emailStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> MaxRows {
        get {
            return this.maxRowsField;
        }
        set {
            this.maxRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SortBy {
        get {
            return this.sortByField;
        }
        set {
            this.sortByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteIDs {
        get {
            return this.websiteIDsField;
        }
        set {
            this.websiteIDsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://addContactTypeToContact.contact.V300")]
public partial class CS_Request6 : CS_Request {
    
    private string contactIDField;
    
    private string contactTypeIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactTypeID {
        get {
            return this.contactTypeIDField;
        }
        set {
            this.contactTypeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://mergeContact.contact.V300")]
public partial class CS_Request4 : CS_Request {
    
    private string altContactIDField;
    
    private string contactIDField;
    
    private string customerNumberField;
    
    private string mergeIntoAltContactIDField;
    
    private string mergeIntoContactIDField;
    
    private string mergeIntoCustomerNumberField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string AltContactID {
        get {
            return this.altContactIDField;
        }
        set {
            this.altContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string MergeIntoAltContactID {
        get {
            return this.mergeIntoAltContactIDField;
        }
        set {
            this.mergeIntoAltContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string MergeIntoContactID {
        get {
            return this.mergeIntoContactIDField;
        }
        set {
            this.mergeIntoContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string MergeIntoCustomerNumber {
        get {
            return this.mergeIntoCustomerNumberField;
        }
        set {
            this.mergeIntoCustomerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://getContactStatus.contact.V300")]
public partial class CS_Request3 : CS_Request {
    
    private string altContactIDField;
    
    private string contactIDField;
    
    private string customerNumberField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string AltContactID {
        get {
            return this.altContactIDField;
        }
        set {
            this.altContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://searchContactTypes.contact.V300")]
public partial class CS_Request2 : CS_Request {
    
    private string contactTypeField;
    
    private string contactTypeIDField;
    
    private System.Nullable<System.DateTime> dateModifiedFromField;
    
    private System.Nullable<System.DateTime> dateModifiedToField;
    
    private System.Nullable<double> maxRowsField;
    
    private System.Nullable<double> pageField;
    
    private string websiteIDsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactType {
        get {
            return this.contactTypeField;
        }
        set {
            this.contactTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactTypeID {
        get {
            return this.contactTypeIDField;
        }
        set {
            this.contactTypeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedFrom {
        get {
            return this.dateModifiedFromField;
        }
        set {
            this.dateModifiedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedTo {
        get {
            return this.dateModifiedToField;
        }
        set {
            this.dateModifiedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> MaxRows {
        get {
            return this.maxRowsField;
        }
        set {
            this.maxRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteIDs {
        get {
            return this.websiteIDsField;
        }
        set {
            this.websiteIDsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://searchShippingAddresses.contact.V300")]
public partial class CS_Request1 : CS_Request {
    
    private string altShippingAddressIDField;
    
    private string contactIDField;
    
    private System.Nullable<System.DateTime> dateModifiedFromField;
    
    private System.Nullable<System.DateTime> dateModifiedToField;
    
    private string isPrimaryField;
    
    private System.Nullable<double> maxRowsField;
    
    private System.Nullable<double> pageField;
    
    private string shippingAddressIDField;
    
    private string websiteIDsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string AltShippingAddressID {
        get {
            return this.altShippingAddressIDField;
        }
        set {
            this.altShippingAddressIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedFrom {
        get {
            return this.dateModifiedFromField;
        }
        set {
            this.dateModifiedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedTo {
        get {
            return this.dateModifiedToField;
        }
        set {
            this.dateModifiedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string IsPrimary {
        get {
            return this.isPrimaryField;
        }
        set {
            this.isPrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> MaxRows {
        get {
            return this.maxRowsField;
        }
        set {
            this.maxRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingAddressID {
        get {
            return this.shippingAddressIDField;
        }
        set {
            this.shippingAddressIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteIDs {
        get {
            return this.websiteIDsField;
        }
        set {
            this.websiteIDsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_GetContactCompletedEventHandler(object sender, CS_GetContactCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_GetContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_GetContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response5 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response5)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_SearchContactTypesCompletedEventHandler(object sender, CS_SearchContactTypesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_SearchContactTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_SearchContactTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response2 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response2)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_MergeContactCompletedEventHandler(object sender, CS_MergeContactCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_MergeContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_MergeContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response4 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response4)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_RemoveContactTypeFromContactCompletedEventHandler(object sender, CS_RemoveContactTypeFromContactCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_RemoveContactTypeFromContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_RemoveContactTypeFromContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response9 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response9)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_AddContactTypeToContactCompletedEventHandler(object sender, CS_AddContactTypeToContactCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_AddContactTypeToContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_AddContactTypeToContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response6 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response6)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_SearchContactsCompletedEventHandler(object sender, CS_SearchContactsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_SearchContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_SearchContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response7 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response7)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_SearchShippingAddressesCompletedEventHandler(object sender, CS_SearchShippingAddressesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_SearchShippingAddressesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_SearchShippingAddressesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response1 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response1)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_GetContactStatusCompletedEventHandler(object sender, CS_GetContactStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_GetContactStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_GetContactStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response3 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response3)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_GetContactTypeCompletedEventHandler(object sender, CS_GetContactTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_GetContactTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_GetContactTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response10 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response10)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_AddUpdateContactTypeCompletedEventHandler(object sender, CS_AddUpdateContactTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_AddUpdateContactTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_AddUpdateContactTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response8 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response8)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CS_SearchMergedContactsCompletedEventHandler(object sender, CS_SearchMergedContactsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CS_SearchMergedContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CS_SearchMergedContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CS_Response11 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CS_Response11)(this.results[0]));
        }
    }
}
