//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="InventoryService.cfcSoapBinding", Namespace="http://V300")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(IS_Error))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(IS_Response))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(IS_Request))]
public partial class IS_InventoryServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback SearchInventoryOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateInventoryOperationCompleted;
    
    /// <remarks/>
    public IS_InventoryServiceService() {
        this.Url = "http://webservices.vin65.com/V300/InventoryService.cfc";
    }
    
    /// <remarks/>
    public event IS_SearchInventoryCompletedEventHandler SearchInventoryCompleted;
    
    /// <remarks/>
    public event IS_UpdateInventoryCompletedEventHandler UpdateInventoryCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("SearchInventoryReturn")]
    public IS_Response2 SearchInventory(IS_Request2 Request) {
        object[] results = this.Invoke("SearchInventory", new object[] {
                    Request});
        return ((IS_Response2)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSearchInventory(IS_Request2 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SearchInventory", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public IS_Response2 EndSearchInventory(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((IS_Response2)(results[0]));
    }
    
    /// <remarks/>
    public void SearchInventoryAsync(IS_Request2 Request) {
        this.SearchInventoryAsync(Request, null);
    }
    
    /// <remarks/>
    public void SearchInventoryAsync(IS_Request2 Request, object userState) {
        if ((this.SearchInventoryOperationCompleted == null)) {
            this.SearchInventoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchInventoryOperationCompleted);
        }
        this.InvokeAsync("SearchInventory", new object[] {
                    Request}, this.SearchInventoryOperationCompleted, userState);
    }
    
    private void OnSearchInventoryOperationCompleted(object arg) {
        if ((this.SearchInventoryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SearchInventoryCompleted(this, new IS_SearchInventoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V300", ResponseNamespace="http://V300")]
    [return: System.Xml.Serialization.SoapElementAttribute("UpdateInventoryReturn")]
    public IS_Response1 UpdateInventory(IS_Request1 Request) {
        object[] results = this.Invoke("UpdateInventory", new object[] {
                    Request});
        return ((IS_Response1)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateInventory(IS_Request1 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateInventory", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public IS_Response1 EndUpdateInventory(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((IS_Response1)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateInventoryAsync(IS_Request1 Request) {
        this.UpdateInventoryAsync(Request, null);
    }
    
    /// <remarks/>
    public void UpdateInventoryAsync(IS_Request1 Request, object userState) {
        if ((this.UpdateInventoryOperationCompleted == null)) {
            this.UpdateInventoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInventoryOperationCompleted);
        }
        this.InvokeAsync("UpdateInventory", new object[] {
                    Request}, this.UpdateInventoryOperationCompleted, userState);
    }
    
    private void OnUpdateInventoryOperationCompleted(object arg) {
        if ((this.UpdateInventoryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateInventoryCompleted(this, new IS_UpdateInventoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName = "Request", Namespace = "http://searchInventory.inventory.V300")]
public partial class IS_Request2 : IS_Request
{

    private string filterField;

    private string inventoryPoolField;

    private string inventoryPoolIDField;

    private System.Nullable<double> maxRowsField;

    private System.Nullable<double> pageField;

    private string sKUField;

    private string websiteIDsField;

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public string Filter
    {
        get
        {
            return this.filterField;
        }
        set
        {
            this.filterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public string InventoryPool
    {
        get
        {
            return this.inventoryPoolField;
        }
        set
        {
            this.inventoryPoolField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public string InventoryPoolID
    {
        get
        {
            return this.inventoryPoolIDField;
        }
        set
        {
            this.inventoryPoolIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public System.Nullable<double> MaxRows
    {
        get
        {
            return this.maxRowsField;
        }
        set
        {
            this.maxRowsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public System.Nullable<double> Page
    {
        get
        {
            return this.pageField;
        }
        set
        {
            this.pageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public string SKU
    {
        get
        {
            return this.sKUField;
        }
        set
        {
            this.sKUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public string WebsiteIDs
    {
        get
        {
            return this.websiteIDsField;
        }
        set
        {
            this.websiteIDsField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapIncludeAttribute(typeof(IS_Request2))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(IS_Request1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://request.base.V300")]
public partial class IS_Request
{

    private IS_Security securityField;

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public IS_Security Security
    {
        get
        {
            return this.securityField;
        }
        set
        {
            this.securityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.base.V300")]
public partial class IS_Security {
    
    private string passwordField;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V300")]
public partial class IS_Error {
    
    private string errorCodeField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapIncludeAttribute(typeof(IS_Response2))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(IS_Response1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V300")]
public partial class IS_Response {
    
    private IS_Error[] errorsField;
    
    private System.Nullable<bool> isSuccessfulField;
    
    private System.Nullable<double> recordCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public IS_Error[] Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsSuccessful {
        get {
            return this.isSuccessfulField;
        }
        set {
            this.isSuccessfulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> RecordCount {
        get {
            return this.recordCountField;
        }
        set {
            this.recordCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://searchInventory.inventory.V300")]
public partial class IS_Response2 : IS_Response {
    
    private IS_Inventory[] inventoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public IS_Inventory[] Inventory {
        get {
            return this.inventoryField;
        }
        set {
            this.inventoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_inventory.inventory.V300")]
public partial class IS_Inventory {
    
    private System.Nullable<double> currentInventoryField;
    
    private string inventoryPoolField;
    
    private string inventoryPoolIDField;
    
    private string sKUField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CurrentInventory {
        get {
            return this.currentInventoryField;
        }
        set {
            this.currentInventoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string InventoryPool {
        get {
            return this.inventoryPoolField;
        }
        set {
            this.inventoryPoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string InventoryPoolID {
        get {
            return this.inventoryPoolIDField;
        }
        set {
            this.inventoryPoolIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://updateInventory.inventory.V300")]
public partial class IS_Response1 : IS_Response {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName = "Request", Namespace = "http://updateInventory.inventory.V300")]
public partial class IS_Request1 : IS_Request
{

    private IS_Inventory inventoryField;

    private string modeField;

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public IS_Inventory Inventory
    {
        get
        {
            return this.inventoryField;
        }
        set
        {
            this.inventoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
    public string Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void IS_SearchInventoryCompletedEventHandler(object sender, IS_SearchInventoryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IS_SearchInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal IS_SearchInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public IS_Response2 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((IS_Response2)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void IS_UpdateInventoryCompletedEventHandler(object sender, IS_UpdateInventoryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IS_UpdateInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal IS_UpdateInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public IS_Response1 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((IS_Response1)(this.results[0]));
        }
    }
}
