//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="OrderService.cfcSoapBinding", Namespace="http://V301")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Tender))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_OrderItem))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_OrderCoupon))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Order))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Error))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Response))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Package))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Request))]
public partial class OS_OrderServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetOrderDetailOperationCompleted;
    
    private System.Threading.SendOrPostCallback PostOrderTrackingOperationCompleted;
    
    private System.Threading.SendOrPostCallback SearchOrdersOperationCompleted;
    
    /// <remarks/>
    public OS_OrderServiceService() {
        this.Url = "http://webservices.vin65.com/V301/OrderService.cfc";
    }
    
    /// <remarks/>
    public event OS_GetOrderDetailCompletedEventHandler GetOrderDetailCompleted;
    
    /// <remarks/>
    public event OS_PostOrderTrackingCompletedEventHandler PostOrderTrackingCompleted;
    
    /// <remarks/>
    public event OS_SearchOrdersCompletedEventHandler SearchOrdersCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V301", ResponseNamespace="http://V301")]
    [return: System.Xml.Serialization.SoapElementAttribute("GetOrderDetailReturn")]
    public OS_Response3 GetOrderDetail(OS_Request3 Request) {
        object[] results = this.Invoke("GetOrderDetail", new object[] {
                    Request});
        return ((OS_Response3)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetOrderDetail(OS_Request3 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetOrderDetail", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public OS_Response3 EndGetOrderDetail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OS_Response3)(results[0]));
    }
    
    /// <remarks/>
    public void GetOrderDetailAsync(OS_Request3 Request) {
        this.GetOrderDetailAsync(Request, null);
    }
    
    /// <remarks/>
    public void GetOrderDetailAsync(OS_Request3 Request, object userState) {
        if ((this.GetOrderDetailOperationCompleted == null)) {
            this.GetOrderDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderDetailOperationCompleted);
        }
        this.InvokeAsync("GetOrderDetail", new object[] {
                    Request}, this.GetOrderDetailOperationCompleted, userState);
    }
    
    private void OnGetOrderDetailOperationCompleted(object arg) {
        if ((this.GetOrderDetailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetOrderDetailCompleted(this, new OS_GetOrderDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V301", ResponseNamespace="http://V301")]
    [return: System.Xml.Serialization.SoapElementAttribute("PostOrderTrackingReturn")]
    public OS_Response2 PostOrderTracking(OS_Request2 Request) {
        object[] results = this.Invoke("PostOrderTracking", new object[] {
                    Request});
        return ((OS_Response2)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostOrderTracking(OS_Request2 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostOrderTracking", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public OS_Response2 EndPostOrderTracking(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OS_Response2)(results[0]));
    }
    
    /// <remarks/>
    public void PostOrderTrackingAsync(OS_Request2 Request) {
        this.PostOrderTrackingAsync(Request, null);
    }
    
    /// <remarks/>
    public void PostOrderTrackingAsync(OS_Request2 Request, object userState) {
        if ((this.PostOrderTrackingOperationCompleted == null)) {
            this.PostOrderTrackingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostOrderTrackingOperationCompleted);
        }
        this.InvokeAsync("PostOrderTracking", new object[] {
                    Request}, this.PostOrderTrackingOperationCompleted, userState);
    }
    
    private void OnPostOrderTrackingOperationCompleted(object arg) {
        if ((this.PostOrderTrackingCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostOrderTrackingCompleted(this, new OS_PostOrderTrackingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://V301", ResponseNamespace="http://V301")]
    [return: System.Xml.Serialization.SoapElementAttribute("SearchOrdersReturn")]
    public OS_Response1 SearchOrders(OS_Request1 Request) {
        object[] results = this.Invoke("SearchOrders", new object[] {
                    Request});
        return ((OS_Response1)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSearchOrders(OS_Request1 Request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SearchOrders", new object[] {
                    Request}, callback, asyncState);
    }
    
    /// <remarks/>
    public OS_Response1 EndSearchOrders(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OS_Response1)(results[0]));
    }
    
    /// <remarks/>
    public void SearchOrdersAsync(OS_Request1 Request) {
        this.SearchOrdersAsync(Request, null);
    }
    
    /// <remarks/>
    public void SearchOrdersAsync(OS_Request1 Request, object userState) {
        if ((this.SearchOrdersOperationCompleted == null)) {
            this.SearchOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOrdersOperationCompleted);
        }
        this.InvokeAsync("SearchOrders", new object[] {
                    Request}, this.SearchOrdersOperationCompleted, userState);
    }
    
    private void OnSearchOrdersOperationCompleted(object arg) {
        if ((this.SearchOrdersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SearchOrdersCompleted(this, new OS_SearchOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://getOrderDetail.order.V301")]
public partial class OS_Request3 : OS_Request {
    
    private string orderIDField;
    
    private System.Nullable<double> orderNumberField;
    
    private System.Nullable<bool> showKitAsIndividualSKUsField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> ShowKitAsIndividualSKUs {
        get {
            return this.showKitAsIndividualSKUsField;
        }
        set {
            this.showKitAsIndividualSKUsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Request3))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Request2))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Request1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.base.V301")]
public partial class OS_Request {
    
    private OS_Security securityField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_Security Security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.base.V301")]
public partial class OS_Security {
    
    private string passwordField;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_orderDetail.order.V301")]
public partial class OS_Tender {
    
    private System.Nullable<double> amountTenderedField;
    
    private System.Nullable<double> cardExpiryMoField;
    
    private System.Nullable<double> cardExpiryYrField;
    
    private string cardNumberField;
    
    private string cardTypeField;
    
    private string giftCardCodeField;
    
    private string giftCardIDField;
    
    private string giftCardNumberField;
    
    private string giftCardVendorField;
    
    private System.Nullable<bool> isActiveField;
    
    private string nameOnCardField;
    
    private System.Nullable<System.DateTime> paymentDateField;
    
    private string paymentStatusField;
    
    private string paymentTermsField;
    
    private string paymentTypeField;
    
    private string pointsIDField;
    
    private System.Nullable<double> pointsRedeemedField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> AmountTendered {
        get {
            return this.amountTenderedField;
        }
        set {
            this.amountTenderedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CardExpiryMo {
        get {
            return this.cardExpiryMoField;
        }
        set {
            this.cardExpiryMoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CardExpiryYr {
        get {
            return this.cardExpiryYrField;
        }
        set {
            this.cardExpiryYrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CardNumber {
        get {
            return this.cardNumberField;
        }
        set {
            this.cardNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CardType {
        get {
            return this.cardTypeField;
        }
        set {
            this.cardTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string GiftCardCode {
        get {
            return this.giftCardCodeField;
        }
        set {
            this.giftCardCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string GiftCardID {
        get {
            return this.giftCardIDField;
        }
        set {
            this.giftCardIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string GiftCardNumber {
        get {
            return this.giftCardNumberField;
        }
        set {
            this.giftCardNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string GiftCardVendor {
        get {
            return this.giftCardVendorField;
        }
        set {
            this.giftCardVendorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsActive {
        get {
            return this.isActiveField;
        }
        set {
            this.isActiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string NameOnCard {
        get {
            return this.nameOnCardField;
        }
        set {
            this.nameOnCardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> PaymentDate {
        get {
            return this.paymentDateField;
        }
        set {
            this.paymentDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PaymentStatus {
        get {
            return this.paymentStatusField;
        }
        set {
            this.paymentStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PaymentTerms {
        get {
            return this.paymentTermsField;
        }
        set {
            this.paymentTermsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PaymentType {
        get {
            return this.paymentTypeField;
        }
        set {
            this.paymentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PointsID {
        get {
            return this.pointsIDField;
        }
        set {
            this.pointsIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> PointsRedeemed {
        get {
            return this.pointsRedeemedField;
        }
        set {
            this.pointsRedeemedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_orderDetail.order.V301")]
public partial class OS_ShipToAddress {
    
    private string addressField;
    
    private string address2Field;
    
    private System.Nullable<System.DateTime> birthDateField;
    
    private string cityField;
    
    private string companyField;
    
    private string countryCodeField;
    
    private string emailField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string phoneField;
    
    private string stateCodeField;
    
    private string titleField;
    
    private string zipCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_orderDetail.order.V301")]
public partial class OS_RMS {
    
    private string batchIDField;
    
    private string cashierIDField;
    
    private string registerNumberField;
    
    private string storeIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string BatchID {
        get {
            return this.batchIDField;
        }
        set {
            this.batchIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CashierID {
        get {
            return this.cashierIDField;
        }
        set {
            this.cashierIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string RegisterNumber {
        get {
            return this.registerNumberField;
        }
        set {
            this.registerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_orderDetail.order.V301")]
public partial class OS_OrderItem {
    
    private System.Nullable<double> costOfGoodField;
    
    private string departmentField;
    
    private string departmentCodeField;
    
    private string inventoryPoolField;
    
    private System.Nullable<bool> isNonTaxableField;
    
    private System.Nullable<bool> isSubSKUField;
    
    private System.Nullable<double> originalPriceField;
    
    private string parentSKUField;
    
    private string parentSKUIDField;
    
    private System.Nullable<double> priceField;
    
    private string productIDField;
    
    private string productSKUIDField;
    
    private System.Nullable<double> quantityField;
    
    private string sKUField;
    
    private System.Nullable<double> salesTaxField;
    
    private System.Nullable<System.DateTime> shippedDateField;
    
    private string shippingSKUField;
    
    private string shippingServiceField;
    
    private string subDepartmentField;
    
    private string subDepartmentCodeField;
    
    private string subTitleField;
    
    private string titleField;
    
    private string trackingNumberField;
    
    private string typeField;
    
    private string unitDescriptionField;
    
    private System.Nullable<double> weightField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CostOfGood {
        get {
            return this.costOfGoodField;
        }
        set {
            this.costOfGoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Department {
        get {
            return this.departmentField;
        }
        set {
            this.departmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string DepartmentCode {
        get {
            return this.departmentCodeField;
        }
        set {
            this.departmentCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string InventoryPool {
        get {
            return this.inventoryPoolField;
        }
        set {
            this.inventoryPoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsNonTaxable {
        get {
            return this.isNonTaxableField;
        }
        set {
            this.isNonTaxableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsSubSKU {
        get {
            return this.isSubSKUField;
        }
        set {
            this.isSubSKUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OriginalPrice {
        get {
            return this.originalPriceField;
        }
        set {
            this.originalPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ParentSKU {
        get {
            return this.parentSKUField;
        }
        set {
            this.parentSKUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ParentSKUID {
        get {
            return this.parentSKUIDField;
        }
        set {
            this.parentSKUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ProductID {
        get {
            return this.productIDField;
        }
        set {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ProductSKUID {
        get {
            return this.productSKUIDField;
        }
        set {
            this.productSKUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> SalesTax {
        get {
            return this.salesTaxField;
        }
        set {
            this.salesTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> ShippedDate {
        get {
            return this.shippedDateField;
        }
        set {
            this.shippedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingSKU {
        get {
            return this.shippingSKUField;
        }
        set {
            this.shippingSKUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingService {
        get {
            return this.shippingServiceField;
        }
        set {
            this.shippingServiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SubDepartment {
        get {
            return this.subDepartmentField;
        }
        set {
            this.subDepartmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SubDepartmentCode {
        get {
            return this.subDepartmentCodeField;
        }
        set {
            this.subDepartmentCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SubTitle {
        get {
            return this.subTitleField;
        }
        set {
            this.subTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string UnitDescription {
        get {
            return this.unitDescriptionField;
        }
        set {
            this.unitDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_orderDetail.order.V301")]
public partial class OS_OrderCoupon {
    
    private string codeField;
    
    private string couponNameField;
    
    private System.Nullable<double> productValueField;
    
    private System.Nullable<double> shippingValueField;
    
    private System.Nullable<double> totalValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CouponName {
        get {
            return this.couponNameField;
        }
        set {
            this.couponNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> ProductValue {
        get {
            return this.productValueField;
        }
        set {
            this.productValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> ShippingValue {
        get {
            return this.shippingValueField;
        }
        set {
            this.shippingValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> TotalValue {
        get {
            return this.totalValueField;
        }
        set {
            this.totalValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://_contact.contact.V301")]
public partial class OS_Contact {
    
    private string addressField;
    
    private string address2Field;
    
    private System.Nullable<System.DateTime> birthDateField;
    
    private string cashierIDField;
    
    private string cityField;
    
    private string companyField;
    
    private string contactIDField;
    
    private string countryCodeField;
    
    private System.Nullable<double> customerNumberField;
    
    private System.Nullable<System.DateTime> dateAddedField;
    
    private System.Nullable<System.DateTime> dateModifiedField;
    
    private string emailField;
    
    private string firstNameField;
    
    private System.Nullable<bool> isNonTaxableField;
    
    private System.Nullable<System.DateTime> lastLoginDateField;
    
    private string lastNameField;
    
    private System.Nullable<System.DateTime> lastOrderDateField;
    
    private System.Nullable<double> lifetimeValueField;
    
    private string masterContactIDField;
    
    private System.Nullable<double> orderCountField;
    
    private string phoneField;
    
    private string sourceCodeField;
    
    private string stateCodeField;
    
    private string titleField;
    
    private string usernameField;
    
    private string websiteIDField;
    
    private string wholesaleNumberField;
    
    private string zipCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CashierID {
        get {
            return this.cashierIDField;
        }
        set {
            this.cashierIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateAdded {
        get {
            return this.dateAddedField;
        }
        set {
            this.dateAddedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModified {
        get {
            return this.dateModifiedField;
        }
        set {
            this.dateModifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsNonTaxable {
        get {
            return this.isNonTaxableField;
        }
        set {
            this.isNonTaxableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> LastLoginDate {
        get {
            return this.lastLoginDateField;
        }
        set {
            this.lastLoginDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> LastOrderDate {
        get {
            return this.lastOrderDateField;
        }
        set {
            this.lastOrderDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> LifetimeValue {
        get {
            return this.lifetimeValueField;
        }
        set {
            this.lifetimeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string MasterContactID {
        get {
            return this.masterContactIDField;
        }
        set {
            this.masterContactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderCount {
        get {
            return this.orderCountField;
        }
        set {
            this.orderCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SourceCode {
        get {
            return this.sourceCodeField;
        }
        set {
            this.sourceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WholesaleNumber {
        get {
            return this.wholesaleNumberField;
        }
        set {
            this.wholesaleNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Order", Namespace="http://_orderDetail.order.V301")]
public partial class OS_Order1 {
    
    private string altOrderNumberField;
    
    private OS_Contact billContactField;
    
    private string clubNameField;
    
    private string clubShipmentNameField;
    
    private System.Nullable<System.DateTime> completedDateField;
    
    private string corporateOrderBatchIDField;
    
    private System.Nullable<double> corporateOrderNumberField;
    
    private System.Nullable<double> depositField;
    
    private string fFSNField;
    
    private string fulfillmentHouseField;
    
    private System.Nullable<System.DateTime> futureShipDateField;
    
    private string giftMessageField;
    
    private System.Nullable<double> handlingField;
    
    private System.Nullable<bool> isAPickupOrderField;
    
    private System.Nullable<bool> isExternalOrderField;
    
    private string marketplaceField;
    
    private OS_OrderCoupon[] orderCouponsField;
    
    private string orderIDField;
    
    private OS_OrderItem[] orderItemsField;
    
    private string orderNotesField;
    
    private System.Nullable<double> orderNumberField;
    
    private string orderStatusField;
    
    private string paymentStatusField;
    
    private string paymentTermsField;
    
    private System.Nullable<System.DateTime> pickupDateField;
    
    private string pickupLocationCodeField;
    
    private System.Nullable<double> previousOrderNumberField;
    
    private string priceLevelField;
    
    private OS_RMS rMSField;
    
    private System.Nullable<System.DateTime> requestedDeliveryDateField;
    
    private System.Nullable<System.DateTime> requestedShipDateField;
    
    private string salesAssociateField;
    
    private string salesAttributeField;
    
    private OS_ShipToAddress shipToAddressField;
    
    private System.Nullable<System.DateTime> shippedDateField;
    
    private System.Nullable<double> shippingField;
    
    private string shippingServiceField;
    
    private string shippingStatusField;
    
    private string shippingTypeField;
    
    private string sourceCodeField;
    
    private System.Nullable<double> subTotalField;
    
    private System.Nullable<System.DateTime> submittedDateField;
    
    private System.Nullable<double> taxField;
    
    private OS_Tender[] tenderField;
    
    private System.Nullable<double> tipField;
    
    private System.Nullable<double> totalField;
    
    private System.Nullable<double> totalAfterTipField;
    
    private string trackingNumberField;
    
    private string transactionTypeField;
    
    private string typeField;
    
    private string websiteIDField;
    
    private string wholesaleNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string AltOrderNumber {
        get {
            return this.altOrderNumberField;
        }
        set {
            this.altOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_Contact BillContact {
        get {
            return this.billContactField;
        }
        set {
            this.billContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ClubName {
        get {
            return this.clubNameField;
        }
        set {
            this.clubNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ClubShipmentName {
        get {
            return this.clubShipmentNameField;
        }
        set {
            this.clubShipmentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> CompletedDate {
        get {
            return this.completedDateField;
        }
        set {
            this.completedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string CorporateOrderBatchID {
        get {
            return this.corporateOrderBatchIDField;
        }
        set {
            this.corporateOrderBatchIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> CorporateOrderNumber {
        get {
            return this.corporateOrderNumberField;
        }
        set {
            this.corporateOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Deposit {
        get {
            return this.depositField;
        }
        set {
            this.depositField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string FFSN {
        get {
            return this.fFSNField;
        }
        set {
            this.fFSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string FulfillmentHouse {
        get {
            return this.fulfillmentHouseField;
        }
        set {
            this.fulfillmentHouseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> FutureShipDate {
        get {
            return this.futureShipDateField;
        }
        set {
            this.futureShipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string GiftMessage {
        get {
            return this.giftMessageField;
        }
        set {
            this.giftMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Handling {
        get {
            return this.handlingField;
        }
        set {
            this.handlingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsAPickupOrder {
        get {
            return this.isAPickupOrderField;
        }
        set {
            this.isAPickupOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsExternalOrder {
        get {
            return this.isExternalOrderField;
        }
        set {
            this.isExternalOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Marketplace {
        get {
            return this.marketplaceField;
        }
        set {
            this.marketplaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_OrderCoupon[] OrderCoupons {
        get {
            return this.orderCouponsField;
        }
        set {
            this.orderCouponsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_OrderItem[] OrderItems {
        get {
            return this.orderItemsField;
        }
        set {
            this.orderItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderNotes {
        get {
            return this.orderNotesField;
        }
        set {
            this.orderNotesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderStatus {
        get {
            return this.orderStatusField;
        }
        set {
            this.orderStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PaymentStatus {
        get {
            return this.paymentStatusField;
        }
        set {
            this.paymentStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PaymentTerms {
        get {
            return this.paymentTermsField;
        }
        set {
            this.paymentTermsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> PickupDate {
        get {
            return this.pickupDateField;
        }
        set {
            this.pickupDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PickupLocationCode {
        get {
            return this.pickupLocationCodeField;
        }
        set {
            this.pickupLocationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> PreviousOrderNumber {
        get {
            return this.previousOrderNumberField;
        }
        set {
            this.previousOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PriceLevel {
        get {
            return this.priceLevelField;
        }
        set {
            this.priceLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_RMS RMS {
        get {
            return this.rMSField;
        }
        set {
            this.rMSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> RequestedDeliveryDate {
        get {
            return this.requestedDeliveryDateField;
        }
        set {
            this.requestedDeliveryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> RequestedShipDate {
        get {
            return this.requestedShipDateField;
        }
        set {
            this.requestedShipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SalesAssociate {
        get {
            return this.salesAssociateField;
        }
        set {
            this.salesAssociateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SalesAttribute {
        get {
            return this.salesAttributeField;
        }
        set {
            this.salesAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_ShipToAddress ShipToAddress {
        get {
            return this.shipToAddressField;
        }
        set {
            this.shipToAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> ShippedDate {
        get {
            return this.shippedDateField;
        }
        set {
            this.shippedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Shipping {
        get {
            return this.shippingField;
        }
        set {
            this.shippingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingService {
        get {
            return this.shippingServiceField;
        }
        set {
            this.shippingServiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingStatus {
        get {
            return this.shippingStatusField;
        }
        set {
            this.shippingStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingType {
        get {
            return this.shippingTypeField;
        }
        set {
            this.shippingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string SourceCode {
        get {
            return this.sourceCodeField;
        }
        set {
            this.sourceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> SubTotal {
        get {
            return this.subTotalField;
        }
        set {
            this.subTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> SubmittedDate {
        get {
            return this.submittedDateField;
        }
        set {
            this.submittedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Tax {
        get {
            return this.taxField;
        }
        set {
            this.taxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_Tender[] Tender {
        get {
            return this.tenderField;
        }
        set {
            this.tenderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Tip {
        get {
            return this.tipField;
        }
        set {
            this.tipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> TotalAfterTip {
        get {
            return this.totalAfterTipField;
        }
        set {
            this.totalAfterTipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WholesaleNumber {
        get {
            return this.wholesaleNumberField;
        }
        set {
            this.wholesaleNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://searchOrders.order.V301")]
public partial class OS_Order {
    
    private string billFirstNameField;
    
    private string billLastNameField;
    
    private System.Nullable<System.DateTime> completedDateField;
    
    private string contactIDField;
    
    private System.Nullable<System.DateTime> dateModifiedField;
    
    private string giftMessageField;
    
    private System.Nullable<bool> isAPickupOrderField;
    
    private System.Nullable<bool> isARMSOrderField;
    
    private System.Nullable<bool> isExternalOrderField;
    
    private System.Nullable<bool> isPendingPickupField;
    
    private string orderIDField;
    
    private string orderNotesField;
    
    private System.Nullable<double> orderNumberField;
    
    private string orderStatusField;
    
    private System.Nullable<double> orderTotalField;
    
    private string paymentStatusField;
    
    private string shipFirstNameField;
    
    private string shipLastNameField;
    
    private string shipStateCodeField;
    
    private System.Nullable<System.DateTime> shippedDateField;
    
    private string shippingStatusField;
    
    private string shippingTypeField;
    
    private System.Nullable<System.DateTime> submittedDateField;
    
    private string trackingNumberField;
    
    private string typeField;
    
    private string websiteIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string BillFirstName {
        get {
            return this.billFirstNameField;
        }
        set {
            this.billFirstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string BillLastName {
        get {
            return this.billLastNameField;
        }
        set {
            this.billLastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> CompletedDate {
        get {
            return this.completedDateField;
        }
        set {
            this.completedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModified {
        get {
            return this.dateModifiedField;
        }
        set {
            this.dateModifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string GiftMessage {
        get {
            return this.giftMessageField;
        }
        set {
            this.giftMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsAPickupOrder {
        get {
            return this.isAPickupOrderField;
        }
        set {
            this.isAPickupOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsARMSOrder {
        get {
            return this.isARMSOrderField;
        }
        set {
            this.isARMSOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsExternalOrder {
        get {
            return this.isExternalOrderField;
        }
        set {
            this.isExternalOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsPendingPickup {
        get {
            return this.isPendingPickupField;
        }
        set {
            this.isPendingPickupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderNotes {
        get {
            return this.orderNotesField;
        }
        set {
            this.orderNotesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderStatus {
        get {
            return this.orderStatusField;
        }
        set {
            this.orderStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderTotal {
        get {
            return this.orderTotalField;
        }
        set {
            this.orderTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PaymentStatus {
        get {
            return this.paymentStatusField;
        }
        set {
            this.paymentStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShipFirstName {
        get {
            return this.shipFirstNameField;
        }
        set {
            this.shipFirstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShipLastName {
        get {
            return this.shipLastNameField;
        }
        set {
            this.shipLastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShipStateCode {
        get {
            return this.shipStateCodeField;
        }
        set {
            this.shipStateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> ShippedDate {
        get {
            return this.shippedDateField;
        }
        set {
            this.shippedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingStatus {
        get {
            return this.shippingStatusField;
        }
        set {
            this.shippingStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingType {
        get {
            return this.shippingTypeField;
        }
        set {
            this.shippingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> SubmittedDate {
        get {
            return this.submittedDateField;
        }
        set {
            this.submittedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteID {
        get {
            return this.websiteIDField;
        }
        set {
            this.websiteIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V301")]
public partial class OS_Error {
    
    private string errorCodeField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Response3))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Response2))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OS_Response1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.base.V301")]
public partial class OS_Response {
    
    private OS_Error[] errorsField;
    
    private System.Nullable<bool> isSuccessfulField;
    
    private System.Nullable<double> recordCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_Error[] Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsSuccessful {
        get {
            return this.isSuccessfulField;
        }
        set {
            this.isSuccessfulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> RecordCount {
        get {
            return this.recordCountField;
        }
        set {
            this.recordCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://getOrderDetail.order.V301")]
public partial class OS_Response3 : OS_Response {
    
    private OS_Order1 orderField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_Order1 Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://postOrderTracking.order.V301")]
public partial class OS_Response2 : OS_Response {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Response", Namespace="http://searchOrders.order.V301")]
public partial class OS_Response1 : OS_Response {
    
    private OS_Order[] ordersField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_Order[] Orders {
        get {
            return this.ordersField;
        }
        set {
            this.ordersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://postOrderTracking.order.V301")]
public partial class OS_Package {
    
    private string carrierField;
    
    private System.Nullable<System.DateTime> shipDateField;
    
    private string trackingNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Carrier {
        get {
            return this.carrierField;
        }
        set {
            this.carrierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> ShipDate {
        get {
            return this.shipDateField;
        }
        set {
            this.shipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://postOrderTracking.order.V301")]
public partial class OS_Request2 : OS_Request {
    
    private System.Nullable<double> orderNumberField;
    
    private OS_Package[] packagesField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OS_Package[] Packages {
        get {
            return this.packagesField;
        }
        set {
            this.packagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(TypeName="Request", Namespace="http://searchOrders.order.V301")]
public partial class OS_Request1 : OS_Request {
    
    private string billFirstNameField;
    
    private string billLastNameField;
    
    private string contactIDField;
    
    private System.Nullable<System.DateTime> dateCompletedFromField;
    
    private System.Nullable<System.DateTime> dateCompletedToField;
    
    private System.Nullable<System.DateTime> dateModifiedFromField;
    
    private System.Nullable<System.DateTime> dateModifiedToField;
    
    private System.Nullable<System.DateTime> dateShippedFromField;
    
    private System.Nullable<System.DateTime> dateShippedToField;
    
    private System.Nullable<System.DateTime> dateSubmittedFromField;
    
    private System.Nullable<System.DateTime> dateSubmittedToField;
    
    private System.Nullable<bool> includeExternalOrdersField;
    
    private System.Nullable<bool> isAPickupOrderField;
    
    private System.Nullable<bool> isARMSOrderField;
    
    private System.Nullable<bool> isPendingPickupField;
    
    private System.Nullable<double> maxRowsField;
    
    private string orderIDField;
    
    private System.Nullable<double> orderNumberField;
    
    private string orderStatusField;
    
    private System.Nullable<double> pageField;
    
    private string paymentStatusField;
    
    private string pickupLocationCodeField;
    
    private string shipFirstNameField;
    
    private string shipLastNameField;
    
    private string shipStateCodeField;
    
    private string shippingStatusField;
    
    private string typeField;
    
    private string websiteIDsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string BillFirstName {
        get {
            return this.billFirstNameField;
        }
        set {
            this.billFirstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string BillLastName {
        get {
            return this.billLastNameField;
        }
        set {
            this.billLastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ContactID {
        get {
            return this.contactIDField;
        }
        set {
            this.contactIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateCompletedFrom {
        get {
            return this.dateCompletedFromField;
        }
        set {
            this.dateCompletedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateCompletedTo {
        get {
            return this.dateCompletedToField;
        }
        set {
            this.dateCompletedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedFrom {
        get {
            return this.dateModifiedFromField;
        }
        set {
            this.dateModifiedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateModifiedTo {
        get {
            return this.dateModifiedToField;
        }
        set {
            this.dateModifiedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateShippedFrom {
        get {
            return this.dateShippedFromField;
        }
        set {
            this.dateShippedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateShippedTo {
        get {
            return this.dateShippedToField;
        }
        set {
            this.dateShippedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateSubmittedFrom {
        get {
            return this.dateSubmittedFromField;
        }
        set {
            this.dateSubmittedFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateSubmittedTo {
        get {
            return this.dateSubmittedToField;
        }
        set {
            this.dateSubmittedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IncludeExternalOrders {
        get {
            return this.includeExternalOrdersField;
        }
        set {
            this.includeExternalOrdersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsAPickupOrder {
        get {
            return this.isAPickupOrderField;
        }
        set {
            this.isAPickupOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsARMSOrder {
        get {
            return this.isARMSOrderField;
        }
        set {
            this.isARMSOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsPendingPickup {
        get {
            return this.isPendingPickupField;
        }
        set {
            this.isPendingPickupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> MaxRows {
        get {
            return this.maxRowsField;
        }
        set {
            this.maxRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string OrderStatus {
        get {
            return this.orderStatusField;
        }
        set {
            this.orderStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<double> Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PaymentStatus {
        get {
            return this.paymentStatusField;
        }
        set {
            this.paymentStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string PickupLocationCode {
        get {
            return this.pickupLocationCodeField;
        }
        set {
            this.pickupLocationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShipFirstName {
        get {
            return this.shipFirstNameField;
        }
        set {
            this.shipFirstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShipLastName {
        get {
            return this.shipLastNameField;
        }
        set {
            this.shipLastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShipStateCode {
        get {
            return this.shipStateCodeField;
        }
        set {
            this.shipStateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string ShippingStatus {
        get {
            return this.shippingStatusField;
        }
        set {
            this.shippingStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string WebsiteIDs {
        get {
            return this.websiteIDsField;
        }
        set {
            this.websiteIDsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void OS_GetOrderDetailCompletedEventHandler(object sender, OS_GetOrderDetailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OS_GetOrderDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal OS_GetOrderDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OS_Response3 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OS_Response3)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void OS_PostOrderTrackingCompletedEventHandler(object sender, OS_PostOrderTrackingCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OS_PostOrderTrackingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal OS_PostOrderTrackingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OS_Response2 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OS_Response2)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void OS_SearchOrdersCompletedEventHandler(object sender, OS_SearchOrdersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OS_SearchOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal OS_SearchOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OS_Response1 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OS_Response1)(this.results[0]));
        }
    }
}
